version: '3.8'

services:
  pix-mcp-server:
    build: .
    container_name: pix-mcp-server
    environment:
      - EFI_CLIENT_ID=${EFI_CLIENT_ID}
      - EFI_CLIENT_SECRET=${EFI_CLIENT_SECRET}
      - EFI_SANDBOX=${EFI_SANDBOX:-true}
      - EFI_PIX_KEY=${EFI_PIX_KEY}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
