services:
  - type: web
    name: pix-mcp-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MCP_MODE
        value: http
      - key: PORT
        value: 10000
      - key: EFI_CLIENT_ID
        sync: false
      - key: EFI_CLIENT_SECRET
        sync: false
      - key: EFI_SANDBOX
        value: true
    healthCheckPath: /health
